name: Construir e Testar

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar Repositório
        uses: actions/checkout@v2

      - name: Configurar JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Construir com Maven
        run: mvn -B clean install

      - name: Executar Testes
        run: mvn test
